version: '3'

services:
  db:
    image: postgres:12-alpine
    volumes: # should be commented when running locally
      - /var/lib/postgresql
    ports:
      - "${DB_PORT}"
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"

  front:
    image: "docker.pkg.github.com/$GITHUB_ORGANIZATION/$FRONT_GITHUB_REPO/$FRONT_GITHUB_PACKAGE:$RELEASE_VERSION"
    command: bash -c "serve -p 3000 -s ."

  api:
    image: "docker.pkg.github.com/$GITHUB_ORGANIZATION/$API_GITHUB_REPO/$API_GITHUB_PACKAGE:$RELEASE_VERSION"
    command: bash -c "bin/squadster start"
    depends_on:
      - db

  bot:
    image: "docker.pkg.github.com/$GITHUB_ORGANIZATION/$BOT_GITHUB_REPO/$BOT_GITHUB_PACKAGE:$RELEASE_VERSION"
    command: bash -c "TODO"
    depends_on:
      - db

  nginx:
    build: nginx
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - api
      - front
