version: '3'

services:
  db:
    image: postgres:12-alpine
    volumes:
      - /var/lib/postgresql
    ports:
      - "${DB_PORT}"
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"

  front:
    image: "docker.pkg.github.com/$GITHUB_ORGANIZATION/$FRONT_GITHUB_REPO/$FRONT_GITHUB_PACKAGE:$RELEASE_VERSION"

  api:
    image: "docker.pkg.github.com/$GITHUB_ORGANIZATION/$API_GITHUB_REPO/$API_GITHUB_PACKAGE:$RELEASE_VERSION"
    links:
      - db

  #nginx:
    #image: "${CI_REGISTRY_IMAGE-local}/nginx:${CI_COMMIT_SHORT_SHA-local}"
    #build:
      #context: .
      #dockerfile: Dockerfile.nginx
    #ports:
      #- "${NGINX_PORT}"
    #links:
      #- api
      #- front

#volumes:
  #postgres:

# TODO: links volumes nginx
